name: Docs

on:
    - push
    - pull_request

jobs:
  build-docs:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest]
          python-version: ['3.10', '3.12']
          
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme
    
    - name: Build documentation
      run: |
        cd docs  # Adjust this to your docs directory
        make html

    - name: Upload GitHub Pages artifact
      uses: actions/upload-artifact@v4
      with:
          name: github-pages
          path: docs/build/html 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html